apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha-factory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpha-factory
  template:
    metadata:
      labels:
        app: alpha-factory
    spec:
      containers:
        - name: alpha-factory
          image: alpha-factory:latest
