apiVersion: apps/v1
kind: Deployment
metadata:
  name: risk-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: risk-engine
  template:
    metadata:
      labels:
        app: risk-engine
    spec:
      containers:
        - name: risk-engine
          image: risk-engine:latest
