apiVersion: v1
kind: Namespace
metadata:
  name: omega-prime
  labels:
    app.kubernetes.io/part-of: omega-prime
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
