apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omega-prime-shared-pvc
  namespace: omega-prime-delta
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
